Repository fever-time/challenge-backend, pull requests merged in 2021-12, with the labels that each got.

#23 1차 스프린트 끝
  README.md
  src/main/java/shop/fevertime/backend/domain/Certification.java
  src/main/java/shop/fevertime/backend/domain/Challenge.java
  src/main/java/shop/fevertime/backend/domain/ChallengeHistory.java
  src/main/java/shop/fevertime/backend/domain/ChallengeStatus.java
  src/main/java/shop/fevertime/backend/domain/Item.java
  src/main/java/shop/fevertime/backend/domain/LocationType.java
  src/main/java/shop/fevertime/backend/domain/Order.java
  src/main/java/shop/fevertime/backend/domain/User.java
  src/main/java/shop/fevertime/backend/dto/request/ChallengeRequestDto.java
  src/main/java/shop/fevertime/backend/dto/response/CertificationResponseDto.java
  src/main/java/shop/fevertime/backend/dto/response/ChallengeResponseDto.java
  src/main/java/shop/fevertime/backend/repository/CertificationRepository.java
  src/main/java/shop/fevertime/backend/service/CertificationService.java
  src/main/java/shop/fevertime/backend/service/ChallengeService.java
  src/main/java/shop/fevertime/backend/service/UserService.java
Labels: CI/CD, 기능구현

#34 피드 댓글 API ( #25 ), 유저 정보 변경 ( #28 )
  src/main/java/shop/fevertime/backend/api/CommentApiController.java
  src/main/java/shop/fevertime/backend/api/FeedApiController.java
  src/main/java/shop/fevertime/backend/api/UserApiController.java
  src/main/java/shop/fevertime/backend/domain/Feed.java
  src/main/java/shop/fevertime/backend/domain/User.java
  src/main/java/shop/fevertime/backend/dto/request/UserRequestDto.java
  src/main/java/shop/fevertime/backend/dto/response/CommentResponseDto.java
  src/main/java/shop/fevertime/backend/dto/response/FeedResponseDto.java
  src/main/java/shop/fevertime/backend/dto/response/UserResponseDto.java
  src/main/java/shop/fevertime/backend/repository/ChallengeRepository.java
  src/main/java/shop/fevertime/backend/repository/CommentRepository.java
  src/main/java/shop/fevertime/backend/service/CommentService.java
  src/main/java/shop/fevertime/backend/service/FeedService.java
  src/main/java/shop/fevertime/backend/service/UserService.java
Labels: 기능구현

#35 챌린지 신청, 신청 취소 (#24) & 챌린지 참여 유저 정보 리스트 (#26)
  build.gradle
  src/main/java/shop/fevertime/backend/api/ChallengeHistoryApiController.java
  src/main/java/shop/fevertime/backend/config/WebSecurityConfig.java
  src/main/java/shop/fevertime/backend/domain/ChallengeHistory.java
  src/main/java/shop/fevertime/backend/domain/User.java
  src/main/java/shop/fevertime/backend/dto/response/ChallengeHistoryResponseDto.java
  src/main/java/shop/fevertime/backend/dto/response/ChallengeUserResponseDto.java
  src/main/java/shop/fevertime/backend/dto/response/UserCertifiesResponseDto.java
  src/main/java/shop/fevertime/backend/repository/CertificationRepository.java
  src/main/java/shop/fevertime/backend/repository/ChallengeHistoryRepository.java
  src/main/java/shop/fevertime/backend/repository/UserRepository.java
  src/main/java/shop/fevertime/backend/service/ChallengeHistoryService.java
Labels: 기능구현

#40 Feat/28 user
  src/main/java/shop/fevertime/backend/api/ChallengeHistoryApiController.java
  src/main/java/shop/fevertime/backend/api/UserApiController.java
  src/main/java/shop/fevertime/backend/domain/User.java
  src/main/java/shop/fevertime/backend/dto/response/UserChallengeResponseDto.java
  src/main/java/shop/fevertime/backend/repository/CertificationRepository.java
  src/main/java/shop/fevertime/backend/repository/ChallengeHistoryRepository.java
  src/main/java/shop/fevertime/backend/repository/ChallengeRepository.java
  src/main/java/shop/fevertime/backend/repository/FeedRepository.java
  src/main/java/shop/fevertime/backend/service/ChallengeHistoryService.java
  src/main/java/shop/fevertime/backend/service/ChallengeService.java
  src/main/java/shop/fevertime/backend/service/UserService.java
Labels: merge

#41 본인 확인 API ( #33 )
  src/main/java/shop/fevertime/backend/api/CertificationApiController.java
  src/main/java/shop/fevertime/backend/api/ChallengeApiController.java
  src/main/java/shop/fevertime/backend/api/ChallengeHistoryApiController.java
  src/main/java/shop/fevertime/backend/api/CommentApiController.java
  src/main/java/shop/fevertime/backend/api/FeedApiController.java
  src/main/java/shop/fevertime/backend/api/UserApiController.java
  src/main/java/shop/fevertime/backend/domain/User.java
  src/main/java/shop/fevertime/backend/dto/response/UserChallengeResponseDto.java
  src/main/java/shop/fevertime/backend/repository/CertificationRepository.java
  src/main/java/shop/fevertime/backend/repository/ChallengeHistoryRepository.java
  src/main/java/shop/fevertime/backend/repository/ChallengeRepository.java
  src/main/java/shop/fevertime/backend/repository/CommentRepository.java
  src/main/java/shop/fevertime/backend/repository/FeedRepository.java
  src/main/java/shop/fevertime/backend/service/CertificationService.java
  src/main/java/shop/fevertime/backend/service/ChallengeHistoryService.java
  src/main/java/shop/fevertime/backend/service/ChallengeService.java
  src/main/java/shop/fevertime/backend/service/CommentService.java
  src/main/java/shop/fevertime/backend/service/FeedService.java
  src/main/java/shop/fevertime/backend/service/UserService.java
Labels: 기능구현, merge

#42 참여 취소 시 인증내역&이미지 삭제 (#36)
  src/main/java/shop/fevertime/backend/service/ChallengeHistoryService.java
Labels: merge

#52 Feed, Comment validation ( #49 )
  src/main/java/shop/fevertime/backend/api/CommentApiController.java
  src/main/java/shop/fevertime/backend/api/FeedApiController.java
  src/main/java/shop/fevertime/backend/domain/Comment.java
  src/main/java/shop/fevertime/backend/domain/Feed.java
  src/main/java/shop/fevertime/backend/exception/ApiException.java
  src/main/java/shop/fevertime/backend/exception/ApiExceptionHandler.java
  src/main/java/shop/fevertime/backend/exception/ApiRequestException.java
  src/main/java/shop/fevertime/backend/repository/CommentRepository.java
  src/main/java/shop/fevertime/backend/repository/FeedRepository.java
  src/main/java/shop/fevertime/backend/service/CommentService.java
  src/main/java/shop/fevertime/backend/service/FeedService.java
  src/main/java/shop/fevertime/backend/util/CommentValidator.java
  src/main/java/shop/fevertime/backend/util/FeedValidator.java
Labels: merge

#53 챌린지, 인증, 유저 validation (#47) & (#49)
  README.md
  src/main/java/shop/fevertime/backend/api/CertificationApiController.java
  src/main/java/shop/fevertime/backend/api/ChallengeApiController.java
  src/main/java/shop/fevertime/backend/api/UserApiController.java
  src/main/java/shop/fevertime/backend/domain/Certification.java
  src/main/java/shop/fevertime/backend/domain/Challenge.java
  src/main/java/shop/fevertime/backend/domain/User.java
  src/main/java/shop/fevertime/backend/dto/request/UserRequestDto.java
  src/main/java/shop/fevertime/backend/exception/ApiExceptionHandler.java
  src/main/java/shop/fevertime/backend/exception/ApiRequestException.java
  src/main/java/shop/fevertime/backend/repository/CertificationRepository.java
  src/main/java/shop/fevertime/backend/repository/ChallengeRepository.java
  src/main/java/shop/fevertime/backend/service/CertificationService.java
  src/main/java/shop/fevertime/backend/service/ChallengeHistoryService.java
  src/main/java/shop/fevertime/backend/service/ChallengeService.java
  src/main/java/shop/fevertime/backend/service/UserService.java
  src/main/java/shop/fevertime/backend/util/CertificationValidator.java
  src/main/java/shop/fevertime/backend/util/ChallengeValidator.java
  src/main/java/shop/fevertime/backend/util/S3Uploader.java
  src/main/java/shop/fevertime/backend/util/UserValidator.java
Labels: merge

#54 spring Rest Docs 추가 (#4)
  build.gradle
  src/docs/asciidoc/api-docs.adoc
  src/main/java/shop/fevertime/backend/config/WebSecurityConfig.java
  src/main/resources/static/docs/api-docs.html
  src/test/java/shop/fevertime/backend/api/ChallengeApiControllerTest.java
  src/test/java/shop/fevertime/backend/api/CommentApiControllerTest.java
  src/test/java/shop/fevertime/backend/api/FeedApiControllerTest.java
Labels: 문서

#56 ci/cd : release1
  .github/workflows/deploy.yml
  src/main/resources/static/docs/api-docs.html
Labels: CI/CD

#57 ci/cd : release 1.0.0
  .ebextensions/00-makeFiles.config
  .github/workflows/deploy.yml
  .github/workflows/docker.yml
  .platform/nginx/nginx.conf
  Dockerfile
  Dockerrun.aws.json
  Procfile
  README.md
  src/main/java/shop/fevertime/backend/service/UserService.java
Labels: CI/CD

#58 ci/cd : release 1.0.1
  src/main/java/shop/fevertime/backend/service/CommentService.java
  src/test/java/shop/fevertime/backend/integration/CertificationIntegrationTest.java
  src/test/java/shop/fevertime/backend/integration/ChallengeHistoryIntegrationTest.java
  src/test/java/shop/fevertime/backend/integration/ChallengeIntegrationTest.java
  src/test/java/shop/fevertime/backend/integration/UserIntegrationTest.java
Labels: CI/CD

#59 ci/cd : release 1.0.2
  src/docs/asciidoc/api-docs.adoc
  src/main/java/shop/fevertime/backend/api/CertificationApiController.java
  src/main/resources/static/docs/api-docs.html
  src/test/java/shop/fevertime/backend/api/CertificationApiControllerTest.java
  src/test/java/shop/fevertime/backend/api/ChallengeApiControllerTest.java
  src/test/java/shop/fevertime/backend/api/CommentApiControllerTest.java
  src/test/java/shop/fevertime/backend/api/FeedApiControllerTest.java
  src/test/java/shop/fevertime/backend/repository/UserRepositoryTest.java
Labels: CI/CD

#62 ci/cd : release 1.0.2
  README.md
  src/main/java/shop/fevertime/backend/domain/Certification.java
  src/main/java/shop/fevertime/backend/domain/Challenge.java
  src/main/java/shop/fevertime/backend/domain/User.java
  src/main/java/shop/fevertime/backend/dto/response/CertificationResponseDto.java
  src/main/java/shop/fevertime/backend/dto/response/ChallengeResponseDto.java
  src/main/java/shop/fevertime/backend/dto/response/ChallengeUserResponseDto.java
  src/main/java/shop/fevertime/backend/dto/response/FeedResponseDto.java
  src/main/java/shop/fevertime/backend/dto/response/UserCertifiesResponseDto.java
  src/main/java/shop/fevertime/backend/dto/response/UserResponseDto.java
  src/main/java/shop/fevertime/backend/exception/ApiExceptionHandler.java
  src/main/java/shop/fevertime/backend/exception/ApiRequestException.java
  src/main/java/shop/fevertime/backend/security/jwt/JwtAuthenticationFilter.java
  src/main/java/shop/fevertime/backend/service/CertificationService.java
  src/main/java/shop/fevertime/backend/service/ChallengeService.java
  src/main/java/shop/fevertime/backend/service/UserService.java
  src/main/java/shop/fevertime/backend/util/CertificationValidator.java
  src/main/java/shop/fevertime/backend/util/ChallengeValidator.java
  src/main/java/shop/fevertime/backend/util/UserValidator.java
  src/main/resources/static/docs/api-docs.html
  src/test/java/shop/fevertime/backend/api/CertificationApiControllerTest.java
  src/test/java/shop/fevertime/backend/api/ChallengeApiControllerTest.java
  src/test/java/shop/fevertime/backend/api/CommentApiControllerTest.java
  src/test/java/shop/fevertime/backend/api/FeedApiControllerTest.java
  src/test/java/shop/fevertime/backend/domain/CertificationTest.java
  src/test/java/shop/fevertime/backend/domain/ChallengeTest.java
  src/test/java/shop/fevertime/backend/domain/UserTest.java
  src/test/java/shop/fevertime/backend/integration/CertificationIntegrationTest.java
  src/test/java/shop/fevertime/backend/integration/ChallengeHistoryIntegrationTest.java
  src/test/java/shop/fevertime/backend/integration/ChallengeIntegrationTest.java
  src/test/java/shop/fevertime/backend/integration/UserIntegrationTest.java
Labels: CI/CD

#65 feat: 챌린지 필터 기능 추가 ( #64 )
  src/main/java/shop/fevertime/backend/api/ChallengeApiController.java
  src/main/java/shop/fevertime/backend/domain/Challenge.java
  src/main/java/shop/fevertime/backend/domain/ChallengeProgress.java
  src/main/java/shop/fevertime/backend/dto/request/ChallengeRequestDto.java
  src/main/java/shop/fevertime/backend/dto/response/ChallengeResponseDto.java
  src/main/java/shop/fevertime/backend/repository/ChallengeRepository.java
  src/main/java/shop/fevertime/backend/service/ChallengeService.java
Labels: 기능 개선

#68 fix: 챌린지 필터 참여자 수 추가( #63 )
  src/main/java/shop/fevertime/backend/dto/response/ChallengeResponseDto.java
  src/main/java/shop/fevertime/backend/service/ChallengeService.java
Labels: 기능 개선

#75 fix: 챌린지 기간 종료시에는 수행이 안 되도록(예외 발생) 수정 ( #64 )
  src/main/java/shop/fevertime/backend/BackendApplication.java
  src/main/java/shop/fevertime/backend/service/ChallengeHistoryService.java
  src/main/java/shop/fevertime/backend/service/ChallengeService.java
Labels: 기능 개선

#76 챌린지 상태 변화 스케줄러 기능 구현 ( #64 )
  src/main/java/shop/fevertime/backend/domain/Challenge.java
  src/main/java/shop/fevertime/backend/service/ChallengeHistoryService.java
  src/main/java/shop/fevertime/backend/service/ChallengeService.java
  src/main/java/shop/fevertime/backend/util/Scheduler.java
Labels: 기능구현

#78 챌린지 종료 시 참여, 취소 불가능, 챌린지 종료 상태변화 추가, 기본 이미지 삭제 방지 추가 ( #63, #64, #70 )
  src/main/java/shop/fevertime/backend/BackendApplication.java
  src/main/java/shop/fevertime/backend/api/ChallengeApiController.java
  src/main/java/shop/fevertime/backend/domain/Challenge.java
  src/main/java/shop/fevertime/backend/domain/ChallengeProgress.java
  src/main/java/shop/fevertime/backend/dto/request/ChallengeRequestDto.java
  src/main/java/shop/fevertime/backend/repository/ChallengeRepository.java
  src/main/java/shop/fevertime/backend/service/ChallengeHistoryService.java
  src/main/java/shop/fevertime/backend/service/ChallengeService.java
  src/main/java/shop/fevertime/backend/service/UserService.java
  src/main/java/shop/fevertime/backend/util/Scheduler.java
Labels: CI/CD

#79 ci/cd : release 1.0.3
  .github/workflows/docker.yml
Labels: CI/CD

#80 ci/cd : release 1.0.4
  .github/workflows/docker.yml
Labels: CI/CD

#81 ci/cd : release 1.0.5
  src/test/java/shop/fevertime/backend/BackendApplicationTests.java
Labels: CI/CD

#82 ci/cd : release 1.0.6
  src/main/java/shop/fevertime/backend/util/Scheduler.java
  src/main/resources/static/docs/api-docs.html
  src/test/java/shop/fevertime/backend/api/CertificationApiControllerTest.java
  src/test/java/shop/fevertime/backend/api/ChallengeApiControllerTest.java
  src/test/java/shop/fevertime/backend/domain/CertificationTest.java
  src/test/java/shop/fevertime/backend/domain/ChallengeHistoryTest.java
  src/test/java/shop/fevertime/backend/domain/ChallengeTest.java
  src/test/java/shop/fevertime/backend/integration/CertificationIntegrationTest.java
  src/test/java/shop/fevertime/backend/integration/ChallengeHistoryIntegrationTest.java
  src/test/java/shop/fevertime/backend/integration/UserIntegrationTest.java
  src/test/java/shop/fevertime/backend/repository/CertificationRepositoryTest.java
  src/test/java/shop/fevertime/backend/repository/ChallengeHistoryRepositoryTest.java
  src/test/java/shop/fevertime/backend/repository/ChallengeRepositoryTest.java
  src/test/java/shop/fevertime/backend/repository/UserRepositoryTest.java
Labels: CI/CD

#84 ci/cd : release 1.0.7
  .github/workflows/docker.yml
  src/main/java/shop/fevertime/backend/dto/request/ChallengeRequestDto.java
  src/main/java/shop/fevertime/backend/service/ChallengeService.java
  src/main/resources/static/docs/api-docs.html
  src/test/java/shop/fevertime/backend/BackendApplicationTests.java
  src/test/java/shop/fevertime/backend/api/ChallengeApiControllerTest.java
Labels: CI/CD

#90 ci/cd : release 1.0.8
  src/main/java/shop/fevertime/backend/config/WebConfig.java
Labels: CI/CD

#91 ci/cd : release 1.0.9
  README.md
  build.gradle
  src/main/java/shop/fevertime/backend/api/CommentApiController.java
  src/main/java/shop/fevertime/backend/domain/Comment.java
  src/main/java/shop/fevertime/backend/repository/CommentRepository.java
  src/main/java/shop/fevertime/backend/service/CommentService.java
  src/main/java/shop/fevertime/backend/util/CommentValidator.java
  src/test/java/shop/fevertime/backend/domain/CommentTest.java
  src/test/java/shop/fevertime/backend/integration/ChallengeHistoryIntegrationTest.java
  src/test/java/shop/fevertime/backend/repository/CommentRepositoryTest.java
Labels: CI/CD

#92 ci/cd : release 1.1.0
  README.md
  src/main/resources/application.yml
Labels: CI/CD

#93 ci/cd : release 1.1.1
  src/main/java/shop/fevertime/backend/service/CertificationService.java
  src/main/java/shop/fevertime/backend/service/ChallengeHistoryService.java
  src/main/java/shop/fevertime/backend/service/ChallengeService.java
  src/main/java/shop/fevertime/backend/service/CommentService.java
  src/main/java/shop/fevertime/backend/service/FeedService.java
  src/main/java/shop/fevertime/backend/service/UserService.java
Labels: CI/CD

#94 ci/cd : release 1.1.2
  src/main/resources/application.yml
  src/test/resources/application.yml
Labels: CI/CD

#97 ci/cd : release 1.1.3
  README.md
  build.gradle
  src/main/java/shop/fevertime/backend/api/AdminApiController.java
  src/main/java/shop/fevertime/backend/config/WebSecurityConfig.java
  src/main/resources/application.yml
  src/main/resources/logback-slack.xml
Labels: CI/CD

#98 ci/cd : release 1.1.4
  src/main/java/shop/fevertime/backend/service/CertificationService.java
  src/main/java/shop/fevertime/backend/service/ChallengeHistoryService.java
  src/main/java/shop/fevertime/backend/service/ChallengeService.java
  src/main/java/shop/fevertime/backend/service/CommentService.java
  src/main/java/shop/fevertime/backend/service/FeedService.java
  src/main/java/shop/fevertime/backend/service/UserService.java
Labels: CI/CD

#99 ci/cd : release 1.1.5
  build.gradle
  src/main/java/shop/fevertime/backend/api/AlarmApiController.java
  src/main/java/shop/fevertime/backend/config/StompHandler.java
  src/main/java/shop/fevertime/backend/config/WebSecurityConfig.java
  src/main/java/shop/fevertime/backend/config/WebSocketConfig.java
  src/main/java/shop/fevertime/backend/dto/MessageDto.java
Labels: CI/CD

#100 ci/cd : release 1.1.5
  build.gradle
  src/main/java/shop/fevertime/backend/api/AlarmApiController.java
  src/main/java/shop/fevertime/backend/config/StompHandler.java
  src/main/java/shop/fevertime/backend/config/WebSecurityConfig.java
  src/main/java/shop/fevertime/backend/config/WebSocketConfig.java
  src/main/java/shop/fevertime/backend/dto/MessageDto.java
Labels: CI/CD

#101 fix: WebSocket 기능 구현 타겟 설정 수정
  src/main/java/shop/fevertime/backend/api/CommentApiController.java
  src/main/java/shop/fevertime/backend/dto/response/CommentResponseDto.java
  src/main/java/shop/fevertime/backend/service/CommentService.java
Labels: 기능 개선

#102 ci/cd : release 1.1.6
  src/main/java/shop/fevertime/backend/api/CommentApiController.java
  src/main/java/shop/fevertime/backend/dto/response/CommentResponseDto.java
  src/main/java/shop/fevertime/backend/service/CommentService.java
Labels: CI/CD

#103 ci/cd : release 1.1.7
  src/main/resources/static/docs/api-docs.html
  src/test/java/shop/fevertime/backend/api/CommentApiControllerTest.java
Labels: CI/CD

#104 ci/cd : release 1.1.8
  src/main/java/shop/fevertime/backend/util/Scheduler.java
Labels: CI/CD

#105 ci/cd : release 1.1.9
  .ebextensions/00-setup-timezone.config
  .github/workflows/docker.yml
Labels: CI/CD

#107 ci/cd : release 1.2.0
  Dockerfile
  src/main/java/shop/fevertime/backend/util/Scheduler.java
Labels: CI/CD

#108 ci/cd : release 1.2.1
  src/main/resources/static/docs/api-docs.html
  src/test/java/shop/fevertime/backend/api/CommentApiControllerTest.java
Labels: 버그, CI/CD

#110 ci/cd : release 1.2.2
  src/docs/asciidoc/api-docs.adoc
Labels: CI/CD
